add segmented control for chart
Sirius-Mobile-2023/GO-Invest pull request #17
Opened 2023-04-14 11:18 UTC by KNPNW

2023-04-14 12:05 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteDetail/SegmentedControl/TimeIntervalsControl.swift
> +    init(intervals: [String]) {
Предлагаю сюда передавать selectedSegmentIndex для того чтобы можно было создать TimeIntervalsControl с любым необходимым первоначально выбранным интервалом и исключить логику установки этого первоначального интервала из TimeIntervalsControl. На 6 строчке значение можно не задавать.
Так как при создании приходит сам список интервалов, то и selectedSegmentIndex там должен быть известен.

2023-04-14 12:20 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteDetail/SegmentedControl/TimeIntervalsControl.swift
> +        stackView.heightAnchor.constraint(equalTo: self.heightAnchor).isActive = true
Для того чтобы постоянно не писать isActive = true можно поместить констрейнты в массив и активировать их все вместе. На 47-48 строках тоже так можно сделать.
```
        let constraints: [NSLayoutConstraint] = [
            selectorView.widthAnchor.constraint(equalTo: segments[selectedSegmentIndex].widthAnchor),
            selectorView.heightAnchor.constraint(equalTo: segments[selectedSegmentIndex].heightAnchor),
            stackView.widthAnchor.constraint(equalTo: self.widthAnchor),
            stackView.heightAnchor.constraint(equalTo: self.heightAnchor)
        ]

        NSLayoutConstraint.activate(constraints)
```

2023-04-14 12:24 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteDetail/SegmentedControl/TimeIntervalsControl.swift
> +    enum Vibration {
Мне кажется этот enum и такое количество кейсов излишни. Можно сразу использовать вместо light  UIImpactFeedbackGenerator(style: .light).impactOccurred() там где это необходимо. Применения других кейсов не нашла.

2023-04-14 13:01 UTC, LyubaxaPro requested changes

2023-04-14 14:39 UTC, LyubaxaPro requested changes

2023-04-14 14:39 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +    let stackView: UIStackView = {
вернем stackView private

2023-04-14 14:39 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailViewController.swift
> +        var constraints: [NSLayoutConstraint] = [
Можно выставление констрейнтов вынести в отдельную функцию

2023-04-14 14:40 UTC, LyubaxaPro requested changes

2023-04-14 14:40 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +    struct Constant {
Constants

2023-04-14 15:33 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +    private var selectedSegmentIndex: Int
При изменении модели надо будет программно менять выбор

2023-04-14 15:34 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +       return view
Что-то с отступами

2023-04-14 15:36 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +        self.setupLayout()
self лишний

2023-04-14 15:37 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +        self.addSubview(stackView)
self лишний

2023-04-14 15:43 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/IntervalButton.swift
> +class IntervalButton: UIButton {
Бесполезный наследник, можно создать convenience initializer в extension'е

2023-04-14 15:45 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +                button.widthAnchor.constraint(equalTo: stackView.heightAnchor)
Кнопки квадратными будут?

2023-04-14 16:00 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +    @objc func buttonTapped(button: UIButton) {
private

2023-04-14 16:07 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +        for (index, btn) in segments.enumerated() {
Надежнее будет если состояние кнопок (UI) будет функцией от selectedSegmentIndex
Здесь достаточно сообщить что нажатие состоялось, а внешний код обновит selectedSegmentIndex

2023-04-14 16:16 UTC, maxibystro requested changes
Надо поправить замечания

2023-04-14 17:05 UTC, KNPNW commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +                button.widthAnchor.constraint(equalTo: stackView.heightAnchor)
Да. Размер квадрата зависит от высоты контрола, единственное надо продумать что делать если высота будет сильно большая и тогда кнопки залезут друг на друга

2023-04-14 18:10 UTC, KNPNW commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +                button.widthAnchor.constraint(equalTo: stackView.heightAnchor)
Сейчас не могу решить одну проблему, поэтому не получается сделать

2023-04-14 18:15 UTC, KNPNW commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/IntervalButton.swift
> +class IntervalButton: UIButton {
Пока сделал extension приватным, так как вроде такой инициализатор больше никому не нужен

2023-04-15 09:49 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +                self.selectorView.frame = self.segments[selectedSegmentIndex].frame
В чем проблема этой строки?

2023-04-15 09:50 UTC, maxibystro requested changes

2023-04-15 09:50 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +                self.selectorView.frame = self.segments[selectedSegmentIndex].frame
В чем проблема этой строки?

2023-04-17 09:51 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/TimeIntervalsControl/TimeIntervalsControl.swift
> +        self.selectedSegmentConstraint.isActive = false
[nit] Много где self лишний
По идее форматер должен справляться, нужно взять свежие изменения из main, там формируется применение форматтера

2023-04-17 11:49 UTC, maxibystro approved these changes

2023-04-17 11:49 UTC, merged