Create UIStackView on Details screen
Sirius-Mobile-2023/GO-Invest pull request #19
Opened 2023-04-14 12:51 UTC by nastyabeggin

Add stack views and mock UI elements

2023-04-14 13:39 UTC, maxibystro requested changes

2023-04-14 13:39 UTC, maxibystro commented on GoInvest/GoInvest/Coordinators/TabBarCoordinator.swift
>      var navigationController: UINavigationController
Вот этот navigationController лишний, но Мустафа уже кажется удалил в своем пуле

2023-04-14 13:39 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailViewController.swift
> +    private let lastDate = UILabel()
lastDate - по названию похоже на дату (тип Date)
Все же нейминг у lastDateLabel лучше
И как раз придется придумать название, чтобы между этими двумя лэйблами была понятна разница другим разарботчикам

2023-04-14 13:39 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailViewController.swift
> +    private let labelStackView = UIStackView()
Лейблов много, по названию непонятно за что именно отвечает stackview

2023-04-14 13:39 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailViewController.swift
> +    private let graphView: UIView = {
Ленивого создания не хватает

2023-04-14 13:55 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailViewController.swift
> +            item.translatesAutoresizingMaskIntoConstraints = false
Это лишнее, stack view сам выставляет

2023-04-14 14:15 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailViewController.swift
> +    private func setupLayout() {
<img width="247" alt="Screen Shot 2023-04-14 at 17 14 22" src="https://user-images.githubusercontent.com/28512113/232069595-59986601-964f-4232-b99b-3a0b7bc02673.png">

2023-04-14 15:27 UTC, nastyabeggin commented
Исправлено

2023-04-15 09:29 UTC, maxibystro approved these changes

2023-04-15 09:30 UTC, merged