make Charts Provider, client for get Points
Sirius-Mobile-2023/GO-Invest pull request #27
Opened 2023-04-15 12:56 UTC by gr-rassadnikov

Get request for get points by fixed date, first 100 points.

2023-04-16 21:33 UTC, LyubaxaPro requested changes

2023-04-16 21:33 UTC, LyubaxaPro commented on GoInvest/GoInvest/Coordinators/QuoteCoordinator.swift
> +                print(quoteCharts.points)
Нам на этом этапе точно нужны points здесь? Не вижу использований.
Если это заглушка для того чтобы при совмещении графика с экраном было понятно как получать точки, надо задуматься так ли она нужна. Если все-таки очень нужна, то в принтах писать отладочную информацию со смыслом (что скрывается за зеленой галочкой и выводимыми точками) + в идеале сверху пометить 
// TODO: #<номер issue, в котором это должно превратиться в конечный код>

2023-04-16 21:33 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteClient/QuoteChartsResult.swift
> +        }
Так как если условие на 13 и на 16 строке не отработает мы возвращаем одну и ту же ошибку их можно объединить в один guard с двумя условиями. Тогда если какое-то из них не выполнится вернем один кейс .failure.

Создание пустого массива points можно перенести после guard чтобы не выполнять лишних действий в случае когда условия не отработают.

2023-04-16 21:33 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteClient/QuoteChartsResult.swift
> +                }
В таком виде нет необходимости выделять условия на 23-24 строках в отдельные скобки, можно писать вот так
```
            if let dateAny = element[safe: dateIndex],
               let priceAny = element[safe: priceIndex],
               let date = dateFromString(str: dateAny.getStringValue()),
               let price = priceAny.getDecimalValue() {
                poinst.append(Point(date, price))
            }
```
Возникает вопрос, не хотим ли мы как-то обработать ситуацию в которой такая большая цепочка обработки почему-то завершилась неудачей?

2023-04-16 21:33 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteClient/QuoteChartsResult.swift
> +    func dateFromString(str: String?) -> Date? {
Полное дублирование с функцией dateFromString  в QuoteCoordinator.  Надо вынести в отдельную сущность и вызывать из нее (желательно сделать такую функцию в этой сущности static).

2023-04-16 21:33 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +            completion: @escaping (_: Result<QuoteCharts, Error>) -> Void
Для Result есть возможность сделать ошибку типизированной (с учетом того что мы возвращаем ошибки только определенного типа).
```
Result<QuoteCharts, ClientError>
```
ClientError соответсвует протоколу Error и поэтому может быть использована в качестве ошибки. Будет удобно при обработке такой ошибки пройтись по всем кейсам ClientError и не рассматривать лишнего.

2023-04-16 21:33 UTC, LyubaxaPro commented on GoInvest/Modules/Sources/QuoteClient/QuoteChartsResult.swift
> +            return .failure(ClientError.incorrectJsonError)
ClientError, а используем не в клиенте. Для работы с графиками можно завести свой enum ошибок.

2023-04-17 12:08 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +        let dateFormatter = DateFormatter()
Форматтер лучше один раз создать, это дорогая операция

2023-04-17 12:09 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +        let urlComponentGetCharts = "https://iss.moex.com/iss/history/engines/stock/markets/shares/boards/\(boardId)/securities/\(id)/candels.json?"
Для сборки урла очень удобен класс urlcomponents https://developer.apple.com/documentation/foundation/urlcomponents

2023-04-17 12:10 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +    private func getHundredtChartsAfterDate(
getHundred**t**ChartsAfterDate

А если биржа будет отдавать 200 точек, то будем переименовывать?

2023-04-17 12:11 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +                callback(.failure(ClientError.getRequestError))
Тут не нужно на главный поток возвращать?

2023-04-17 12:12 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +                callback(.failure(ClientError.getRequestError))
Можно сделать один метод, который будет синхронно выполнять замыкание если уже на главном потоке, и будет шедулить на главную очередь в противном случае

2023-04-17 12:13 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +                case let .success(quotCharts):
quot**e**Charts

2023-04-17 12:13 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +                        if points.count > 1 {
Почему здесь 1, а не 0?

2023-04-17 13:24 UTC, gr-rassadnikov commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +                        if points.count > 1 {
запросы посылалось не правильно (первая и последняя запись между запросами - повторялись).
Исправил добавление start = 0/1 в url запрhса.

2023-04-17 13:24 UTC, gr-rassadnikov commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +                case let .success(quotCharts):
fix

2023-04-17 13:26 UTC, gr-rassadnikov commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +    private func getHundredtChartsAfterDate(
fix

2023-04-17 13:27 UTC, gr-rassadnikov commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +        let urlComponentGetCharts = "https://iss.moex.com/iss/history/engines/stock/markets/shares/boards/\(boardId)/securities/\(id)/candels.json?"
сделал urlcomponents, везде где это было бы рационально

2023-04-17 13:31 UTC, gr-rassadnikov commented on GoInvest/Modules/Sources/QuoteClient/QuoteClient.swift
> +        let dateFormatter = DateFormatter()
fix

2023-04-17 15:24 UTC, maxibystro commented
Конфликты

2023-04-18 15:02 UTC, maxibystro approved these changes

2023-04-18 15:02 UTC, merged