12 - Add SwiftUI graph with mock data
Sirius-Mobile-2023/GO-Invest pull request #33
Opened 2023-04-17 12:30 UTC by VislovIvan

2023-04-17 13:45 UTC, maxibystro requested changes

2023-04-17 13:45 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +struct GraphViewController: View {
ViewController - это из мира UIKit
В swiftUI используется термин View
Здесь в итоге GraphView

2023-04-17 13:45 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +    @State var currentTab: String = "7 Days"
GraphView не должен знать про "табы", этот термин зависит от UI, который может поменяться
Тут скорее interval
И планируется ли использовать это свойство?

2023-04-17 13:45 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +/* // Временное решение, для данных из сети оно будет изменено.
Вот такой комментарий нужен
// TODO: __таска_в_которой_будет_исправлено__

2023-04-17 13:45 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +    @State var isLineGraph: Bool = false
Тип Bool можно не указывать

2023-04-17 13:45 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +    @State var isLineGraph: Bool = false
Свойство не используется

2023-04-17 13:45 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +    var animate: Bool = false
Нет смысла для каждой точки указывать

2023-04-17 13:47 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +        .chartYScale(domain: 0...(15000))
А если надо будет построить график с ценами от 1 до 30 ?

2023-04-17 18:18 UTC, VislovIvan commented on GoInvest/Modules/Sources/QuoteDetail/GraphViewController.swift
> +        .chartYScale(domain: 0...(15000))
Добавил верхний порог графика по максимальной цене, минимальная цена отображается адаптивно

2023-04-19 12:51 UTC, maxibystro requested changes

2023-04-19 12:51 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailView.swift
> +    private let graphView: UIHostingController<GraphView> = {
UIHostingController - это наследник UIViewController.
UIView не должна знать про UIViewController, потому что контроллер вьюшки знает про вьюшку, не наоборот

Можно передавать вьюшку в int'е или сделать свойство / метод, позволяющий добавить вьюшку графика

2023-04-19 12:51 UTC, maxibystro commented on GoInvest/Modules/Sources/QuoteDetail/QuoteDetailViewController.swift
> +    private let graphView = UIHostingController(rootView: GraphView())
Тут второй раз создается контроллер.
Кажется это та проблема, с которой вчера разбирались

Здесь как раз правильно место для контроллера.
Родительский контроллер знает о своем child контроллере - это ок

2023-04-19 21:45 UTC, maxibystro approved these changes

2023-04-19 21:45 UTC, merged