28 create strategy screen/knpnw
Sirius-Mobile-2023/GO-Invest pull request #39
Opened 2023-04-18 09:17 UTC by KNPNW

2023-04-18 12:03 UTC, LyubaxaPro requested changes

2023-04-18 12:27 UTC, LyubaxaPro approved these changes

2023-04-18 13:15 UTC, VislovIvan commented on GoInvest/Modules/Sources/Strategy/StrategyViewController.swift
> +        scrollView.contentSize = CGSize(width: self.view.frame.width, height: self.view.frame.height + 700)
адаптировать scrollView для всех размеров данных

2023-04-19 13:37 UTC, maxibystro commented on GoInvest/Modules/Sources/Strategy/StrategyView.swift
> +            amountView.heightAnchor.constraint(equalToConstant: 50),
[nit] Констрейнты на высоту все-таки лишние

2023-04-19 13:47 UTC, merged